# 站点配置

# 导入主题
# theme: jekyll-theme-chirpy # 指定使用的 Jekyll 主题，这里是 chirpy
theme: jekyll-theme-chirpy

# 网页语言 › http://www.lingoes.net/en/translator/langcode.htm
# 如果它与 `_data/locales` 文件夹中的某个文件名相同，布局语言也会更改，
# 否则，布局语言将使用默认值 'en'。
lang: zh-CN # 网站主要语言，这里是简体中文

# 更改为你的时区 › https://kevinnovak.github.io/Time-Zone-Picker
timezone: Asia/Shanghai # 设置时区，例如：Asia/Shanghai, America/New_York

# jekyll-seo-tag 插件设置 › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------

title: Chirpy # 网站主标题，会显示在浏览器标签页等地
tagline: This is a simple website # 网站副标题或标语
description: >- # 网站描述，用于 SEO meta 标签和 Atom feed
  Just try 1 try

# 填写你站点的协议和主机名。
# 例如 'https://username.github.io'，注意末尾不要加 '/'。
url: "https://domopy.github.io" # 网站的完整 URL，非常重要，用于生成绝对链接

github:
  username: domopy # 你的 GitHub 用户名
twitter:
  username: twitter_username # 你的 Twitter 用户名 (如果使用)

social:
  # 更改为你的全名。
  # 它将显示为文章的默认作者和页脚的版权所有者。
  name: domopy # 你的名字或昵称，用于作者和版权
  email: domo12345678@163.com # 你的电子邮件地址
  links:
    # 第一个元素作为版权所有者的链接
    # - https://twitter.com/username # 你的 Twitter 主页
    - https://github.com/domopy # 你的 GitHub 主页
    # 取消注释以添加更多社交链接
    # - https://www.facebook.com/username
    # - https://www.linkedin.com/in/username

# 网站验证设置 (用于搜索引擎站长工具)
webmaster_verifications:
  google: # 你的 Google 验证码
  bing: # 你的 Bing 验证码
  alexa: # 你的 Alexa 验证码
  yandex: # 你的 Yandex 验证码
  baidu: # 你的百度验证码
  facebook: # 你的 Facebook 验证码

# ↑ --------------------------
# `jekyll-seo-tag` 设置结束

# Web 分析设置
analytics:
  google:
    id: # 你的 Google Analytics ID, 例如 UA-XXXXXXXXX-X 或 G-XXXXXXXXXX
  goatcounter:
    id: # 你的 GoatCounter ID
  umami:
    id: # 你的 Umami ID
    domain: # 你的 Umami 域名
  matomo:
    id: # 你的 Matomo ID
    domain: # 你的 Matomo 域名
  cloudflare:
    id: # 你的 Cloudflare Web Analytics token
  fathom:
    id: # 你的 Fathom Site ID

# 页面浏览量设置
pageviews:
  provider: # 目前仅支持 'goatcounter'

# 颜色主题偏好设置。
#
# 注意：留空将默认遵循系统偏好颜色，
# 并且在侧边栏左下角会有一个切换主题（暗色/亮色）的按钮。
#
# 可用选项:
# light — 使用亮色主题
# dark — 使用暗色主题
#
theme_mode: # [light | dark] 例如: light

# 媒体资源的 CDN 端点。
# 注意，一旦指定，CDN url 将被添加到所有以 '/' 开头的媒体资源路径（站点头像、文章图片、音视频文件）。
#
# 例如 'https://cdn.com'
cdn:

# 侧边栏头像，支持本地或 CORS 资源
avatar: /assets/img/testimg.jpg # 你的头像图片路径, 例如 /assets/img/avatar.jpg

# 在 SEO `og:image` 元标记中使用的网站级社交预览图像的 URL。
# 可以在 front matter 中通过自定义 `page.image` 覆盖。
social_preview_image: # 字符串，本地或 CORS 资源, 例如 /assets/img/preview.png

# 布尔类型，文章中目录 (TOC) 的全局开关。
toc: true # 是否默认开启文章目录

comments:
  # 文章评论系统的全局开关。留空表示禁用。
  provider: # [disqus | utterances | giscus] 例如: giscus
  # 提供者选项如下：
  disqus:
    shortname: # 填写 Disqus shortname › https://help.disqus.com/en/articles/1717111-what-s-a-shortname
  # utterances 设置 › https://utteranc.es/
  utterances:
    repo: # <gh-username>/<repo> 例如: domopy/my-blog-comments
    issue_term: pathname # < url | pathname | title | ...>
  # Giscus 选项 › https://giscus.app
  giscus:
    repo: domopy/your-repo-for-giscus # <gh-username>/<repo> 你的 Giscus 仓库
    repo_id: # 你的 Giscus 仓库 ID
    category: # 你的 Giscus 分类名
    category_id: # 你的 Giscus 分类 ID
    mapping: pathname # 可选, 默认为 'pathname'
    strict: 0 # 可选, 默认为 '0'
    input_position: bottom # 可选, 默认为 'bottom'
    lang: # 可选, 默认为 `site.lang` 的值
    reactions_enabled: 1 # 可选, 默认为 `1`

# 自托管静态资源, 可选 › https://github.com/cotes2020/chirpy-static-assets
assets:
  self_host:
    enabled: false # 布尔值, 留空表示 false, 是否开启自托管静态资源
    # 指定 Jekyll 环境, 留空表示两者都适用
    # 仅当 `assets.self_host.enabled` 为 'true' 时生效
    env: # [development | production]

pwa: # Progressive Web App (PWA) 设置
  enabled: true # PWA 功能（可安装）选项
  cache:
    enabled: true # PWA 离线缓存选项
    # 此处定义的路径将从 PWA 缓存中排除。
    # 通常它的值是与当前网站共享相同域名的另一个网站的 `baseurl`。
    deny_paths:
      # - "/example"  # 匹配 `<SITE_URL>/example/*` 的 URL 将不会被 PWA 缓存

paginate: 10 # 分页：每页显示的文章数量

# 你的站点的根路径 (base URL)
# 如果你的网站部署在子目录下，例如 'https://username.github.io/myblog'，则应设置为 '/myblog'
# 如果部署在根域名下，则留空 "" 或设置为 "/"
baseurl: "" # 如果你的博客在 example.com/blog, 则这里是 "/blog"

# ------------ 以下选项不建议修改 ------------------

kramdown: # Markdown 解析器 kramdown 的配置
  footnote_backlink: "&#8617;&#xfe0e;" #脚注返回链接的符号
  syntax_highlighter: rouge # 语法高亮器
  syntax_highlighter_opts: # Rouge 选项 › https://github.com/jneen/rouge#full-options
    css_class: highlight # 高亮代码块的 CSS 类名
    # default_lang: console # 默认语言
    span:
      line_numbers: false # span 元素是否显示行号
    block:
      line_numbers: true # block 元素是否显示行号
      start_line: 1 # 起始行号

collections: # Jekyll Collections 设置
  tabs: # Chirpy 主题使用的自定义集合，用于创建顶部导航标签页
    output: true # 是否为这个集合中的每个文档生成单独的页面
    sort_by: order # 按 `order` 字段排序

defaults: # 为特定类型或路径的文件设置 Front Matter 默认值
  - scope:
      path: "" # 空字符串表示项目中的所有文件
      type: posts # 作用于 `posts` 类型
    values:
      layout: post # 帖子默认布局
      comments: true # 帖子默认启用评论
      toc: true # 帖子默认显示目录
      # 除非你非常有把握更新项目中所有其他文章链接的代码，否则不要修改以下参数。
      permalink: /posts/:title/ # 帖子永久链接格式
  - scope:
      path: _drafts # 作用于 `_drafts` 目录
    values:
      comments: false # 草稿默认禁用评论
  - scope:
      path: ""
      type: tabs # 作用于 `tabs` 类型 (见 `site.collections`)
    values:
      layout: page # 标签页默认布局
      permalink: /:title/ # 标签页永久链接格式

sass: # SASS/SCSS 编译器设置
  style: compressed # 输出的 CSS 样式，compressed 表示压缩

compress_html: # HTML 压缩设置
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development] # 在开发环境中忽略 HTML 压缩

exclude: # Jekyll 构建时排除的文件/文件夹列表
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"

jekyll-archives: # jekyll-archives 插件设置，用于生成归档页 (分类、标签)
  enabled: [categories, tags] # 启用分类和标签归档
  layouts:
    category: category # 分类归档页使用的布局
    tag: tag # 标签归档页使用的布局
  permalinks:
    tag: /tags/:name/ # 标签归档页的永久链接格式
    category: /categories/:name/ # 分类归档页的永久链接格式